language: go
go:
    - "1.11.x"
services:
    - mongodb
    - docker
install:
    - go get -t ./...
    - sudo apt-get -y install python3 python3-pip
script:
    - "[ $(make fmt | wc -l) == 0 ]"
    - make all
    - make test
before_deploy:
    - make docs
    - make container
deploy:
    - provider: script
      script: bash -c "make container-push"
      on:
        branch: master
