language: go
go:
    - "1.11.x"
services:
    - mongodb
    - docker
install:
    - go get -t ./...
    - sudo apt-get -y install python3 python3-pip
script:
    - "[ $(gofmt -l . | wc -l) == 0 ]"
    - make all
    - make test
before_deploy:
    - make docs
    - make container
deploy:
    - provider: s3
      access_key_id: $HACKILLINOIS_ACCESS_KEY
      secret_access_key: $HACKILLINOIS_SECRET_KEY
      bucket: hackillinois-api
      skip_cleanup: true
      local_dir: deploy
      on:
        branch: master
    - provider: s3
      access_key_id: $HACKILLINOIS_ACCESS_KEY
      secret_access_key: $HACKILLINOIS_SECRET_KEY
      bucket: hackillinois-api-docs
      skip-cleanup: true
      local_dir: documentation/site
      on:
        branch: master
