language: go
go:
    - "1.11.x"
env:
    - GO111MODULE=on
services:
    - mongodb
    - docker
install:
    - sudo apt-get -y install python3 python3-pip
script:
    - "[ $(make fmt | wc -l) == 0 ]"
    - make all
    - make test
before_deploy:
    - make docs
    - make container TAG=$TRAVIS_TAG
deploy:
    - provider: script
      script: bash -c "make container-push TAG=$TRAVIS_TAG"
      on:
        branch: master
