version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=461497099412.dkr.ecr.us-east-1.amazonaws.com/hackillinois-api-event
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t hackillinois-api-event .
      - docker tag hackillinois-api-event $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hackillinois-api-event","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
